### PR TITLE
add: gotoBOF, gotoEOF, killToBOF, killToEOF,

### PR DESCRIPTION
**Pull request by iyefrat**
I think these would be useful.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by iyefrat** [comment]
@jtdaugherty Hey, can you make a new release of the library?

**Comment by jtdaugherty** [comment]
Done; this change is now released in `0.11`.

**Comment by iyefrat** [comment]
Thank you!

**Pull request merged**
