### PR TITLE
Adds functions to inspect the Char at cursor

### PR DESCRIPTION
**Pull request by kritzcreek**
I found I needed these to write any meaningful combinators and thought they might provide value to someone else.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks for the patch! I'd be happy to merge this if you can modify the new functions to return `Maybe Char` instead, and return `Nothing` instead of `'\n'`. Newlines are not actually valid characters in the text editor; they are only returned when the underlying text is reconstructed. Using `Maybe` forces the user to handle this special case (which is easy to forget if `Char` is returned).

**Comment by kritzcreek** [comment]
Funnily enough that was my initial API, but because the remaining module didn't have any `Maybe`s I wanted to make it consistent ;) If this looks fine I can squash.

**Comment by jtdaugherty** [comment]
Thanks for updating the patch. Are there other functions of the existing API that you think would benefit from returning `Maybe`? I don't see any that return `Char` to begin with, so I don't know which ones you might be thinking of.

**Comment by kritzcreek** [comment]
After taking another look it's pretty much just `moveCursor` that gave that impression to me.

**Comment by jtdaugherty** [comment]
Right now we have
```
moveCursor :: Monoid a => (Int, Int) -> TextZipper a -> TextZipper a
```
What do you have in mind for this? If it returned `Maybe`, what would that indicate?

**Comment by kritzcreek** [comment]
Nothing would indicate that the given position was not found within the
TextZipper.

Am 16.01.2017 6:07 nachm. schrieb "Jonathan Daugherty" <
notifications@github.com>:

**Comment by jtdaugherty** [comment]
I see. I didn't return `Maybe` from `moveCursor` because I'd rather use `Maybe` to indicate *failure*, and I don't think an attempt to move the cursor to an illegal position is a failure because it can be safely ignored. I figured that `moveCursor` would be more useful if it did this rather than fail, although if a failing `moveCursor` was important then we could always have
```
safeMoveCursor :: Monoid a => (Int, Int) -> TextZippper a -> Maybe (TextZipper a)

moveCursor :: Monoid a => (Int, Int) -> TextZippper a -> TextZipper a
moveCursor pos z = maybe z id $ safeMoveCursor pos z
```

**Comment by kritzcreek** [comment]
No strong preference from my side. I'd prefer the API you outlined in the previous comment, but it would in no way influence the content in this PR.

**Comment by jtdaugherty** [comment]
Okay. In that case, since I don't need that myself, I'll merge this and if you want that other API then I'd be happy to consider a patch. Thanks!

**Comment by kritzcreek** [comment]
Thanks!

**Pull request merged**
